INSERT INTO dim_participante (NU_INSCRICAO, NU_ANO, TP_FAIXA_ETARIA, TP_SEXO, TP_ESTADO_CIVIL, TP_COR_RACA, TP_NACIONALIDADE, TP_ST_CONCLUSAO, TP_ANO_CONCLUIU, TP_ENSINO, IN_TREINEIRO)
SELECT 
    NU_INSCRICAO,
    NU_ANO, 
    TP_FAIXA_ETARIA, 
    TP_SEXO,         
    TP_ESTADO_CIVIL, 
    TP_COR_RACA,     
    TP_NACIONALIDADE,
    TP_ST_CONCLUSAO,
    TP_ANO_CONCLUIU, 
    TP_ENSINO,       
    IN_TREINEIRO 
FROM dados_enem_2020;

INSERT INTO dim_escola (CO_MUNICIPIO_ESC, NO_MUNICIPIO_ESC, CO_UF_ESC, SG_UF_ESC, TP_DEPENDENCIA_ADM_ESC, TP_LOCALIZACAO_ESC, TP_SIT_FUNC_ESC)
SELECT 
	CO_MUNICIPIO_ESC,
	NO_MUNICIPIO_ESC,
	CO_UF_ESC,
	SG_UF_ESC,
	TP_DEPENDENCIA_ADM_ESC,
	TP_LOCALIZACAO_ESC,
	TP_SIT_FUNC_ESC
FROM dados_enem_2020;


INSERT INTO dim_aplicacao_prova (CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, CO_UF_PROVA, SG_UF_PROVA)
SELECT
	CO_MUNICIPIO_PROVA,
	NO_MUNICIPIO_PROVA,
	CO_UF_PROVA,
	SG_UF_PROVA
FROM dados_enem_2020;

INSERT INTO dim_prova_objetiva (TP_PRESENCA_CN, TP_PRESENCA_CH, TP_PRESENCA_LC, TP_PRESENCA_MT, CO_PROVA_CN, CO_PROVA_CH, CO_PROVA_LC, CO_PROVA_MT, NU_NOTA_CH, NU_NOTA_CN, NU_NOTA_LC, NU_NOTA_MT, TX_RESPOSTAS_CN ,TX_RESPOSTAS_CH ,TX_RESPOSTAS_LC, TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC, TX_GABARITO_MT)
SELECT 
	TP_PRESENCA_CN,
	TP_PRESENCA_CH, 
	TP_PRESENCA_LC, 
	TP_PRESENCA_MT, 
	CO_PROVA_CN, 
	CO_PROVA_CH, 
	CO_PROVA_LC, 
	CO_PROVA_MT, 
	NU_NOTA_CH, 
	NU_NOTA_CN, 
	NU_NOTA_LC, 
	NU_NOTA_MT, 
	TX_RESPOSTAS_CN, 
	TX_RESPOSTAS_CH,
	TX_RESPOSTAS_LC,
	TX_RESPOSTAS_MT,
	TP_LINGUA,
	TX_GABARITO_CN,
	TX_GABARITO_CH,
	TX_GABARITO_LC,
	TX_GABARITO_MT
FROM dados_enem_2020;


INSERT INTO dim_redacao (TP_STATUS_REDACAO, NU_NOTA_COMP1, NU_NOTA_COMP2, NU_NOTA_COMP3, NU_NOTA_COMP4, NU_NOTA_COMP5, NU_NOTA_REDACAO)
SELECT 
	TP_STATUS_REDACAO,
	NU_NOTA_COMP1,
	NU_NOTA_COMP2,
	NU_NOTA_COMP3,
	NU_NOTA_COMP4,
	NU_NOTA_COMP5,
	NU_NOTA_REDACAO
FROM dados_enem_2020;

INSERT INTO dim_q_se (Q001, Q002, Q003, Q004, Q005, Q006, Q007, Q008, Q009, Q010, Q011, Q012, Q013, Q014, Q015, Q016, Q017, Q018, Q019, Q020, Q021, Q022, Q023, Q024, Q025)
SELECT 
	Q001,
	Q002,
	Q003,
	Q004,
	Q005, 
	Q006,
	Q007,
	Q008,
	Q009,
	Q010,
	Q011, 
	Q012, 
	Q013, 
	Q014, 
	Q015, 
	Q016, 
	Q017, 
	Q018, 
	Q019,
	Q020,
	Q021,
	Q022,
	Q023,
	Q024, 
	Q025
FROM dados_enem_2020;


INSERT INTO fato_identificadores (ID_PARTICIPANTE, ID_ESCOLA, ID_APLICACAO_PROVA, ID_PROVA_OBJETIVA, ID_REDACAO, ID_Q_SE)
SELECT 
    dp.ID_PARTICIPANTE,
	de.ID_ESCOLA,
	dap.ID_APLICACAO_PROVA,
	dpo.ID_PROVA_OBJETIVA,
	dr.ID_REDACAO,
	dqs.ID_Q_SE
FROM dados_enem_2020
LEFT JOIN dim_participante dp ON dp.ID_PARTICIPANTE = dados_enem_2020.ID_TABELA
LEFT JOIN dim_escola de ON de.ID_ESCOLA = dados_enem_2020.ID_TABELA
LEFT JOIN dim_aplicacao_prova dap ON dap.ID_APLICACAO_PROVA = dados_enem_2020.ID_TABELA
LEFT JOIN dim_prova_objetiva dpo ON dpo.ID_PROVA_OBJETIVA = dados_enem_2020.ID_TABELA
LEFT JOIN dim_redacao dr ON dr.ID_REDACAO = dados_enem_2020.ID_TABELA
LEFT JOIN dim_q_se dqs ON dqs.ID_Q_SE = dados_enem_2020.ID_TABELA