CREATE TABLE [dim_participante] (
  [ID_PARTICIPANTE] INT PRIMARY KEY IDENTITY,
  [NU_INSCRICAO] BIGINT UNIQUE,
  [NU_ANO] INT,
  [TP_FAIXA_ETARIA] INT,
  [TP_SEXO] VARCHAR(2),
  [TP_ESTADO_CIVIL] VARCHAR(2),
  [TP_COR_RACA] INT,
  [TP_NACIONALIDADE] INT,
  [TP_ST_CONCLUSAO] INT,
  [TP_ANO_CONCLUIU] INT,
  [TP_ENSINO] INT,
  [IN_TREINEIRO] BIT
);


CREATE TABLE [dim_escola] (
  [ID_ESCOLA] INT PRIMARY KEY IDENTITY,
  [CO_MUNICIPIO_ESC] INT,
  [NO_MUNICIPIO_ESC] VARCHAR(255),
  [CO_UF_ESC] INT,
  [SG_UF_ESC] VARCHAR(10),
  [TP_DEPENDENCIA_ADM_ESC] INT,
  [TP_LOCALIZACAO_ESC] INT,
  [TP_SIT_FUNC_ESC] INT
);


CREATE TABLE [dim_aplicacao_prova] (
  [ID_APLICACAO_PROVA] INT PRIMARY KEY IDENTITY,
  [CO_MUNICIPIO_PROVA] INT,
  [NO_MUNICIPIO_PROVA] VARCHAR(150),
  [CO_UF_PROVA] VARCHAR(2),
  [SG_UF_PROVA] VARCHAR(2)
);

CREATE TABLE [dim_prova_objetiva] (
  [ID_PROVA_OBJETIVA] INT PRIMARY KEY IDENTITY,
  [TP_PRESENCA_CN] INT,
  [TP_PRESENCA_CH] INT,
  [TP_PRESENCA_LC] INT,
  [TP_PRESENCA_MT] INT,
  [CO_PROVA_CN] INT,
  [CO_PROVA_CH] INT,
  [CO_PROVA_LC] INT,
  [CO_PROVA_MT] INT,
  [NU_NOTA_CH] INT,
  [NU_NOTA_CN] INT,
  [NU_NOTA_LC] INT,
  [NU_NOTA_MT] INT,
  [TX_RESPOSTAS_CN] VARCHAR(50),
  [TX_RESPOSTAS_CH] VARCHAR(50),
  [TX_RESPOSTAS_LC] VARCHAR(50),
  [TX_RESPOSTAS_MT] VARCHAR(50),
  [TP_LINGUA] BIT,
  [TX_GABARITO_CN] VARCHAR(50),
  [TX_GABARITO_CH] VARCHAR(50),
  [TX_GABARITO_LC] VARCHAR(50),
  [TX_GABARITO_MT] VARCHAR(50)
);


CREATE TABLE [dim_redacao] (
  [ID_REDACAO] INT PRIMARY KEY IDENTITY,
  [TP_STATUS_REDACAO] INT,
  [NU_NOTA_COMP1] INT,
  [NU_NOTA_COMP2] INT,
  [NU_NOTA_COMP3] INT,
  [NU_NOTA_COMP4] INT,
  [NU_NOTA_COMP5] INT,
  [NU_NOTA_REDACAO] INT
);

CREATE TABLE [dim_q_se] (
  [ID_Q_SE] INT PRIMARY KEY IDENTITY,
  [Q001] VARCHAR(1),
  [Q002] VARCHAR(1),
  [Q003] VARCHAR(1),
  [Q004] VARCHAR(1),
  [Q005] VARCHAR(1),
  [Q006] VARCHAR(1),
  [Q007] VARCHAR(1),
  [Q008] VARCHAR(1),
  [Q009] VARCHAR(1),
  [Q010] VARCHAR(1),
  [Q011] VARCHAR(1),
  [Q012] VARCHAR(1),
  [Q013] VARCHAR(1),
  [Q014] VARCHAR(1),
  [Q015] VARCHAR(1),
  [Q016] VARCHAR(1),
  [Q017] VARCHAR(1),
  [Q018] VARCHAR(1),
  [Q019] VARCHAR(1),
  [Q020] VARCHAR(1),
  [Q021] VARCHAR(1),
  [Q022] VARCHAR(1),
  [Q023] VARCHAR(1),
  [Q024] VARCHAR(1),
  [Q025] VARCHAR(1)
);


CREATE TABLE [fato_resultado] (
  [ID_RESULTADO] INT PRIMARY KEY IDENTITY,
  [ID_PARTICIPANTE] INT,
  [ID_ESCOLA] INT,
  [ID_APLICACAO_PROVA] INT,
  [ID_PROVA_OBJETIVA] INT,
  [ID_REDACAO] INT,
  [ID_Q_SE] INT,
  FOREIGN KEY ([ID_PARTICIPANTE]) REFERENCES [dim_participante]([ID_PARTICIPANTE]),
  FOREIGN KEY ([ID_ESCOLA]) REFERENCES [dim_escola]([ID_ESCOLA]),
  FOREIGN KEY ([ID_APLICACAO_PROVA]) REFERENCES [dim_aplicacao_prova]([ID_APLICACAO_PROVA]),
  FOREIGN KEY ([ID_PROVA_OBJETIVA]) REFERENCES [dim_prova_objetiva]([ID_PROVA_OBJETIVA]),
  FOREIGN KEY ([ID_REDACAO]) REFERENCES [dim_redacao]([ID_REDACAO]),
  FOREIGN KEY ([ID_Q_SE]) REFERENCES [dim_q_se]([ID_Q_SE])
);